{
  "taskDefinition": {
    "family": "demo-repo",
    "containerDefinitions": [
    {
      "name": "demo-repo",
      "image": "622267634686.dkr.ecr.us-east-2.amazonaws.com/demorepo:latest",
      "cpu": 100,
      "portMappings": [
      {
        "protocol": "tcp",
        "containerPort": 80,
        "hostPort": 80
      }
      ],
      "memory": 128,
      "essential": true
    }
    ]
  }
}