version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting the build"
    build:
      commands:
      - mvn install
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - buildspec.yml