version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting the build"
    build:
      commands:
      - mvn package
  post_build:
    commands:
      - echo "Build completed"
artificats:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar