version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting the build"
    build:
      commands:
      - mvn install
  post_build:
    commands:
      - echo "Build completed"
      - ls ./target/demo-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - ./target/demo-0.0.1-SNAPSHOT.jar